language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: xBqgEsP7Oj3LQAnVG9HygwzvFNgjZQnEvcFsX1uVIUWo7Eo/akJuZXPdnOUFUBhOzfPfkPexUAK5D30F4wNBdFIPA7OrK0kfsvwIWIgzP5Teys+ILFR12IX+A8PA8VAA515WRX9x7BBwEdZ/FzLdaEDehfcNhKwPl8LgSpV1CzkdlUAXpHEXhwjGDgXEqu70cXmIdpqWHr8i893cNz8VVD1UDSn9oUVh4R8/mTQ7bIfRMli8q3MDo8Rl9n8XDhRQI0526VAFVSoPy8c1d0Kx1ghB5D38CAe1mmHE36lfa8gbmCkLAUfehO/baAkOGYDp/EOh0QcrXKa5YflnaKPdTelblTmIWfbboV+fK65hiqY4isTcr3DMGR1TXhvdvs+e5TXqXJotAyZ2j7wbUMWme7NuZI9fIBpC4qPJpMhmXvF4P0ZHCyYaH1W0/buxtXfBepwBGgWAk4nLaC+gugB56GtHf09Wogw/QHIvtMSe1/b+xZONbBpcfkcjKGCj7XvxV0lyEoi+cX6Iz3vh3OIAcnnXv74iS+6e6FuZBGZTG3PYQfmShnar3Bj1TWVp/gU/dvKY2BpHwYUT9RgUWL+arXZNlDLJ/zAk4h24fgpIn1kfUpbSHSTXOkVAGnFIXE4ozHPDrme5NlA3pdl88s3WtopxHwg0jlX0so3PzP3ftq4=
  app: afternoon-beach-43611
  on:
    repo: staysee/blog_app_mongoose_tests
